spring:
  #数据库链接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterSetResults=utf8&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: "yyw,19960731"
  #jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
#日志
logging:
  level:
    root: warn
    com.ywknight.blog: info
  file:
    name: blog-pro.log
    path: ../blog/
server:
  port: 80
