spring:
  #数据库链接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  #jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#日志
logging:
  level:
    root: info
    com.ywknight.blog: debug
  file:
    name: blog-dev.log
    path: ./../blog/

server:
  port: 8090